# Generated by Django 5.2.5 on 2025-11-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0017_hoadon_chitiethoadon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='khoi_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
