# Generated by Django 5.2.5 on 2025-11-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_alter_sanpham_khoi_tao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
