# Generated by Django 5.2.5 on 2025-12-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0020_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='address',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='duong',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='phuong',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='quan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='so_nha',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='tinh',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
